version: 2.1
workflows: 
  deploy: 
    jobs: 
      - deploy: 
        context: keys

jobs: 
  deploy: 
    docker: 
      - image: cimg/base:2021.04
    resource_class: small
    steps: 
      - checkout
      - run: git clone https://github.com/william-exe-v4/williamv4org-about.git
      - run: rm -rf ./williamv4org-about/resume.html
      - run: mv index.html ./williamv4org-about/resume.html
      - run: git commit -m "resume update"
      - run: cd williamv4org-about
      - run: git push https://william-exe-v4-circleci:$amogus@github.com/william-exe-v4/williamv4org-about.git